/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as CoasRouteImport } from './routes/coas'
import { Route as ShopRouteImport } from './routes/shop'
import { Route as OrderNumberRouteImport } from './routes/order.$number'
import { Route as ProductsSlugRouteImport } from './routes/products.$slug'
import { Route as ApiPublicAuthorizeNetWebhookRouteImport } from './routes/api/public/authorize-net.webhook'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const CoasRoute = CoasRouteImport.update({
  id: '/coas',
  path: '/coas',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopRoute = ShopRouteImport.update({
  id: '/shop',
  path: '/shop',
  getParentRoute: () => rootRouteImport,
} as any)
const OrderNumberRoute = OrderNumberRouteImport.update({
  id: '/order/$number',
  path: '/order/$number',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsSlugRoute = ProductsSlugRouteImport.update({
  id: '/products/$slug',
  path: '/products/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicAuthorizeNetWebhookRoute =
  ApiPublicAuthorizeNetWebhookRouteImport.update({
    id: '/api/public/authorize-net/webhook',
    path: '/api/public/authorize-net/webhook',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/checkout': typeof CheckoutRoute
  '/coas': typeof CoasRoute
  '/shop': typeof ShopRoute
  '/order/$number': typeof OrderNumberRoute
  '/products/$slug': typeof ProductsSlugRoute
  '/api/public/authorize-net/webhook': typeof ApiPublicAuthorizeNetWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/checkout': typeof CheckoutRoute
  '/coas': typeof CoasRoute
  '/shop': typeof ShopRoute
  '/order/$number': typeof OrderNumberRoute
  '/products/$slug': typeof ProductsSlugRoute
  '/api/public/authorize-net/webhook': typeof ApiPublicAuthorizeNetWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/checkout': typeof CheckoutRoute
  '/coas': typeof CoasRoute
  '/shop': typeof ShopRoute
  '/order/$number': typeof OrderNumberRoute
  '/products/$slug': typeof ProductsSlugRoute
  '/api/public/authorize-net/webhook': typeof ApiPublicAuthorizeNetWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/checkout'
    | '/coas'
    | '/shop'
    | '/order/$number'
    | '/products/$slug'
    | '/api/public/authorize-net/webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/checkout'
    | '/coas'
    | '/shop'
    | '/order/$number'
    | '/products/$slug'
    | '/api/public/authorize-net/webhook'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/checkout'
    | '/coas'
    | '/shop'
    | '/order/$number'
    | '/products/$slug'
    | '/api/public/authorize-net/webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  CheckoutRoute: typeof CheckoutRoute
  CoasRoute: typeof CoasRoute
  ShopRoute: typeof ShopRoute
  OrderNumberRoute: typeof OrderNumberRoute
  ProductsSlugRoute: typeof ProductsSlugRoute
  ApiPublicAuthorizeNetWebhookRoute: typeof ApiPublicAuthorizeNetWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/coas': {
      id: '/coas'
      path: '/coas'
      fullPath: '/coas'
      preLoaderRoute: typeof CoasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop': {
      id: '/shop'
      path: '/shop'
      fullPath: '/shop'
      preLoaderRoute: typeof ShopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/order/$number': {
      id: '/order/$number'
      path: '/order/$number'
      fullPath: '/order/$number'
      preLoaderRoute: typeof OrderNumberRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/$slug': {
      id: '/products/$slug'
      path: '/products/$slug'
      fullPath: '/products/$slug'
      preLoaderRoute: typeof ProductsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/authorize-net/webhook': {
      id: '/api/public/authorize-net/webhook'
      path: '/api/public/authorize-net/webhook'
      fullPath: '/api/public/authorize-net/webhook'
      preLoaderRoute: typeof ApiPublicAuthorizeNetWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  CheckoutRoute: CheckoutRoute,
  CoasRoute: CoasRoute,
  ShopRoute: ShopRoute,
  OrderNumberRoute: OrderNumberRoute,
  ProductsSlugRoute: ProductsSlugRoute,
  ApiPublicAuthorizeNetWebhookRoute: ApiPublicAuthorizeNetWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
